# Определяем фазы сборки
[phases.setup]
# Указываем пакеты, которые нужно установить в окружение сборки
# nixPkgs = ["...", "..."] # Можно оставить пустым, Nixpacks сам определит Node.js

[phases.install]
# Команда для установки зависимостей. Nixpacks сам поймет, что это npm.
# cmd = "npm ci" # Можно оставить пустым или явно указать

[phases.build]
# Команда для сборки. Nixpacks сам поймет, что это npm.
# cmd = "npm run build" # Можно оставить пустым или явно указать

# --- КЛЮЧЕВАЯ ЧАСТЬ: Команда запуска ---
[start]
# Указываем команду, которая будет запускать приложение ПОСЛЕ сборки
# И здесь важно, чтобы Nixpacks "знал", что нужно запускать из папки backend
cmd = "cd backend && npm run start"